version: '3'
services:
  broker:
    image: rabbitmq:management
    container_name: broker
    ports:
      - "5672:5672"  # Port untuk AMQP
      - "15672:15672"  # Port untuk RabbitMQ Management UI
    volumes:
      - "./static/rabbitmq-data:/var/lib/rabbitmq" 
    environment:
      RABBITMQ_DEFAULT_USER: "user"  # Ganti dengan nama pengguna yang Anda inginkan
      RABBITMQ_DEFAULT_PASS: "password"